import { Experience, Education, Stack, Project } from "./types";

export class AppConstants {
  static readonly numberOfExperience = 4;
  static readonly numberOfClients = 5;

  static readonly workExperience: Experience[] = [
    {
      id: 1,
      dates: "03/2023 - 03/2024",
      title: "SOFTWARE DEVELOPER",
      company: "SPREELOOP S.A.R.L",
      location: "Douala, Cameroon",
      responsibilities: [
        "Responsible for the maintenance of existing applications;",
        "Design, build and maintain new software solutions (from bank-end services to front-end integration);",
        "Prototyping user interface for web using React js framework;",
        "Solve problems and bugs efficiently;",
        "Writing unit, widget and integration testing for our flutter code and for backend using TS & JS;",
        "Report and solve any issue on existing application;",
        "Documenting code and code review;",
      ],
      techStack: [
        "Scrum Methodology",
        "Typescript",
        "React",
        "Javascript",
        "Flutter",
        "Dart",
        "Firebase",
        "FireCMS",
        "Cloud functions",
        "Node js",
        "Git",
        "Unit testing",
        "Widget testing",
        "Integration testing",
      ],
    },
    {
      id: 2,
      dates: "11/2021 - 10/2022",
      title: "JUNIOR SOFTWARE DEVELOPER",
      company: "APPSKILL Consulting",
      location: "Bafoussam (Remote)",
      responsibilities: [
        "Responsible for the quick development of an android application on the frontend;",
        "Unit testing mobile applications;",
        "Code review;",
      ],
      techStack: [
        "Scrum Methodology",
        "Kotlin",
        "Java",
        "Gradle",
        "Git",
        "Github",
        "VS Code",
        "Android Studio",
      ],
    },
  ];

  static readonly education: Education[] = [
    {
      id: 1,
      dates: "01/2020 - 01/2022",
      degree: "Bachelor's degree",
      field: "Electrical Engineering",
      institution: "FOTSO VICTOR University institute of technolog",
      location: "Bandjoun",
    },
    {
      id: 2,
      dates: "01/2017 - 01/2020",
      degree: "National Diploma",
      field: "Thermal and Renewable Energy",
      institution: "FOTSO VICTOR University institute of technolog",
      location: "Bandjoun",
    },
    {
      id: 3,
      dates: "01/2014 - 01/2016",
      degree: "GCE-A Level",
      field: "Science",
      institution: "Saint Paul's Comprehensive College",
      location: "Bamenda",
    },
  ];

  static readonly stacks: Stack[] = [
    {
      id: 1,
      name: "React",
      description: "Frontend Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
      skillLevel: 50,
      category: "Frameworks & Libraries",
    },
    {
      id: 2,
      name: "TypeScript",
      description: "Programming Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
      skillLevel: 80,
      category: "Languages",
    },
    {
      id: 3,
      name: "JavaScript",
      description: "Programming Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
      skillLevel: 70,
      category: "Languages",
    },
    {
      id: 4,
      name: "Flutter",
      description: "Mobile Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flutter/flutter-original.svg",
      skillLevel: 90,
      category: "Frameworks & Libraries",
    },
    {
      id: 5,
      name: "Node.js",
      description: "Backend Runtime",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
      skillLevel: 80,
      category: "Tools & Platform",
    },
    {
      id: 6,
      name: "Firebase",
      description: "Backend Service",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-plain.svg",
      skillLevel: 65,
      category: "Tools & Platform",
    },
    {
      id: 7,
      name: "Git",
      description: "Version Control",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
      skillLevel: 60,
      category: "Tools & Platform",
    },
    {
      id: 8,
      name: "Docker",
      description: "Containerization",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
      skillLevel: 60,
      category: "Tools & Platform",
    },

    {
      id: 9,
      name: "Kotlin",
      description: "Programming Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kotlin/kotlin-original.svg",
      skillLevel: 80,
      category: "Languages",
    },
    {
      id: 10,
      name: "Java",
      description: "Programming Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg",
      skillLevel: 75,
      category: "Languages",
    },
    {
      id: 11,
      name: "NestJS",
      description: "Backend Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nestjs/nestjs-original.svg",
      skillLevel: 90,
      category: "Frameworks & Libraries",
    },
    {
      id: 12,
      name: "Express",
      description: "Backend Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg",
      skillLevel: 70,
      category: "Frameworks & Libraries",
    },
    {
      id: 13,
      name: "AWS",
      description: "Cloud Service",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg",
      skillLevel: 70,
      category: "Tools & Platform",
    },
    {
      id: 14,
      name: "GCP",
      description: "Cloud Service",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/googlecloud/googlecloud-original.svg",
      skillLevel: 60,
      category: "Tools & Platform",
    },
    {
      id: 15,
      name: "MySQL",
      description: "Database",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg",
      skillLevel: 60,
      category: "Databases",
    },
    {
      id: 16,
      name: "PostgreSQL",
      description: "Database",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
      skillLevel: 60,
      category: "Databases",
    },
    {
      id: 17,
      name: "MongoDB",
      description: "Database",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
      skillLevel: 60,
      category: "Databases",
    },
    {
      id: 18,
      name: "SQLite",
      description: "Database",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlite/sqlite-original.svg",
      skillLevel: 60,
      category: "Databases",
    },
    {
      id: 19,
      name: "DynamoDB",
      description: "Database",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dynamodb/dynamodb-original.svg",
      skillLevel: 60,
      category: "Databases",
    },
    {
      id: 20,
      name: "dart",
      description: "Programming Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dart/dart-original.svg",
      skillLevel: 90,
      category: "Languages",
    },
    {
      id: 21,
      name: "Spring Boot",
      description: "Backend Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/spring/spring-original.svg",
      skillLevel: 70,
      category: "Frameworks & Libraries",
    },
    {
      id: 22,
      name: "Prisma",
      description: "ORM",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg",
      skillLevel: 70,
      category: "Tools & Platform",
    },
    {
      id: 23,
      name: "Pulumi",
      description: "Infrastructure as Code",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pulumi/pulumi-original.svg",
      skillLevel: 60,
      category: "Frameworks & Libraries",
    },
    {
      id: 23,
      name: "Tailwind CSS",
      description: "CSS Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
      skillLevel: 60,
      category: "Frameworks & Libraries",
    },
    {
      id: 24,
      name: "HTML",
      description: "Markup Language",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
      skillLevel: 60,
      category: "Languages",
    },
    {
      id: 25,
      name: "CSS",
      description: "CSS Framework",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
      skillLevel: 60,
      category: "Languages",
    },
    {
      id: 26,
      name: "Figma",
      description: "Design Tool",
      icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg",
      skillLevel: 70,
      category: "Tools & Platform",
    },
  ];

  static readonly featuredProjects: Project[] = [
    {
      id: 1,
      name: "Korí pro",
      description:
        "A mobile application that brings beauty professionals close to their clients. This is the professional version app designed for beauty service providers to manage their business and connect with customers.",
      category: "Beauty & Wellness",
      pageCount: 28,
      previewImage: "/projects/kori-pro/kori-pro-preview-1.png",
      images: [
        {
          id: 1,
          image: "/projects/kori-pro/kori-pro-preview-2.png",
          description: "Korí pro preview",
        },
        {
          id: 2,
          image: "/projects/kori-pro/kori-pro-0x2.png",
          description: "Korí pro welcome screen",
        },
        {
          id: 3,
          image: "/projects/kori-pro/kori-pro-1x1.png",
          description: "Korí pro agenda page",
        },
        {
          id: 4,
          image: "/projects/kori-pro/kori-pro-2x1.png",
          description: "Korí pro salon detail screen",
        },
        {
          id: 5,
          image: "/projects/kori-pro/kori-pro-3x1.png",
          description: "Korí pro service offering location",
        },
        {
          id: 6,
          image: "/projects/kori-pro/kori-pro-4x1.png",
          description: "Korí pro select types of services",
        },
      ],
      logo: "/projects/kori-pro/kori-pro-logo.png",
      backgroundGradient: "from-pink-400 to-white",
      deviceType: "mobile",
      osTypes: ["ios", "android"],
      functionality:
        "Comprehensive beauty service management platform with appointment scheduling, client management, payment processing, and real-time notifications. Backend integrates GCP for cloud services, AWS for additional infrastructure, NestJS for API management, PostgreSQL for data persistence, and Pulumi for infrastructure as code.",
      repoLink: "https://github.com/kori-beauty/kori",
      techStack: [
        "Flutter",
        "Dart",
        "GCP",
        "AWS",
        "Node.js",
        "NestJS",
        "PostgreSQL",
        "Pulumi",
        "Prisma",
      ],
    },
    {
      id: 2,
      name: "Korí",
      description:
        "The customer-facing mobile application that connects beauty enthusiasts with professional beauty service providers. Users can discover, book, and manage beauty appointments with verified professionals in their area.",
      category: "Beauty & Wellness",
      pageCount: 24,
      previewImage: "/projects/kori/kori-preview-1.png",
      images: [
        {
          id: 1,
          image: "/projects/kori/kori-preview-2.png",
          description: "Korí app preview",
        },
        {
          id: 2,
          image: "/projects/kori/kori-1x1.png",
          description: "Korí welcome screen",
        },
        {
          id: 3,
          image: "/projects/kori/kori-6x1.png",
          description: "Korí favorite discovery screen",
        },
        {
          id: 4,
          image: "/projects/kori/kori-2x1.png",
          description: "Korí reservation screen",
        },
        {
          id: 5,
          image: "/projects/kori/kori-3x1.png",
          description: "Korí salon detail screen",
        },
        {
          id: 6,
          image: "/projects/kori/kori-4x1.png",
          description: "Korí service selection screen",
        },
      ],
      logo: "/projects/kori/kori-logo.png",
      backgroundGradient: "from-yellow-400 to-white",
      deviceType: "mobile",
      osTypes: ["ios", "android"],
      functionality:
        "Customer-focused beauty service marketplace with real-time booking, location-based service discovery, secure payment processing, and review system. Backend integrates GCP for cloud services, AWS for additional infrastructure, NestJS for API management, PostgreSQL for data persistence, and Pulumi for infrastructure as code.",
      repoLink: "https://github.com/kori-beauty/kori",
      techStack: [
        "Flutter",
        "Dart",
        "GCP",
        "AWS",
        "Node.js",
        "NestJS",
        "PostgreSQL",
        "Pulumi",
        "Prisma",
      ],
    },
    {
      id: 3,
      name: "Vegetable Market",
      description:
        "A clean, modern demo website for a local vegetable shop, showcasing fresh produce along with nutritional information, seasonal availability, and helpful cooking tips for each vegetable.",
      category: "E-commerce & Local Business",
      pageCount: 1,
      previewImage: "/projects/vegetable-market/m-vegetables-preview.png",
      images: [
        {
          id: 1,
          image: "/projects/vegetable-market/m-vegetables-preview.png",
          description: "Vegetable Market Homepage",
        },
        {
          id: 2,
          image: "/projects/vegetable-market/m-vegetables-1.png",
          description: "Mobile View – Catalog",
        },
        {
          id: 3,
          image: "/projects/vegetable-market/m-vegetables-2.png",
          description: "Mobile View – Product Details",
        },
        {
          id: 4,
          image: "/projects/vegetable-market/m-vegetables-3.png",
          description: "Mobile View – Nutritional Info",
        },
        {
          id: 5,
          image: "/projects/vegetable-market/m-vegetables-4.png",
          description: "Mobile View – Cooking Tips",
        },
        {
          id: 6,
          image: "/projects/vegetable-market/m-vegetables-5.png",
          description: "Mobile View – Seasonal Indicators",
        },
        {
          id: 7,
          image: "/projects/vegetable-market/m-vegetables-6.png",
          description: "Mobile View – Responsive Layout",
        },
      ],
      logo: "/projects/vegetable-market/favicon.ico",
      backgroundGradient: "from-green-400 to-white",
      deviceType: "desktop",
      osTypes: ["web"],
      functionality:
        "This is a demo website and is not fully functional yet. It features a responsive layout, a visually appealing vegetable catalog, and sections for nutritional information, seasonal availability, and cooking tips. The project is built with **HTML** for semantic structure, **CSS** and **Tailwind CSS** for fast and consistent styling, **JavaScript** for interactive elements, and **TypeScript** for type safety and maintainability. Together, these technologies ensure clean code, scalability, and a smooth user experience across devices.",
      repoLink: "https://github.com/kodage111/vegetable_market",
      liveLink: "https://vegetable-market-six.vercel.app/",
      techStack: ["HTML", "CSS", "JavaScript", "Tailwind CSS", "TypeScript"],
    },
    {
      id: 4,
      name: "GEC S.A.R.L",
      description:
        "A professional corporate website for GEC S.A.R.L, a BTP (Building and Public Works) company, featuring a modern dark theme design that showcases their construction services, projects portfolio, and company information.",
      category: "Corporate & Business",
      pageCount: 8,
      previewImage: "/projects/gec/gec-preview.png",
      images: [
        {
          id: 1,
          image: "/projects/gec/gec-2.png",
          description: "GEC S.A.R.L Homepage",
        },
        {
          id: 2,
          image: "/projects/gec/gec-3.png",
          description: "GEC S.A.R.L Services",
        },
        {
          id: 3,
          image: "/projects/gec/gec-4.png",
          description: "GEC S.A.R.L Projects",
        },
        {
          id: 4,
          image: "/projects/gec/gec-5.png",
          description: "GEC S.A.R.L About",
        },
        {
          id: 5,
          image: "/projects/gec/gec-6.png",
          description: "GEC S.A.R.L Contact",
        },
        {
          id: 6,
          image: "/projects/gec/gec-7.png",
          description: "GEC S.A.R.L Dark Theme",
        },
        {
          id: 7,
          image: "/projects/gec/gec-8.png",
          description: "GEC S.A.R.L Mobile View",
        },
        {
          id: 8,
          image: "/projects/gec/gec-9.png",
          description: "GEC S.A.R.L Portfolio",
        },
        {
          id: 9,
          image: "/projects/gec/gec-10.png",
          description: "GEC S.A.R.L Team",
        },
      ],
      logo: "/projects/gec/gec-logo.png",
      backgroundGradient: "from-lime-400 to-white",
      deviceType: "desktop",
      osTypes: ["web"],
      functionality:
        "Professional corporate website with dark theme implementation, responsive design, and comprehensive company showcase including services, project portfolio, team information, and contact details. Built with modern React components and styled with Tailwind CSS for optimal performance and user experience.",
      repoLink: "https://github.com/kodage111/gec_sarl/",
      liveLink: "https://gec-sarl-g8nb.vercel.app/",
      techStack: ["React", "CSS", "HTML", "Tailwind CSS", "JavaScript"],
    },
    {
      id: 5,
      name: "Assurance Contract Handler",
      description:
        "A native Android mobile application designed to help insurance companies streamline their operations by importing and managing Excel files, organizing customer data, and tracking contract expirations with automated reminders.",
      logo: "/projects/ach/ach-logo.png",
      category: "File management",
      pageCount: 10,
      previewImage: "/projects/ach/ach-preview-2.png",
      images: [
        {
          id: 1,
          image: "/projects/ach/ach-preview.png",
          description: "Dashboard Overview",
        },
        {
          id: 2,
          image: "/projects/ach/ach-1.jpg",
          description: "Excel Import Interface",
        },
        {
          id: 3,
          image: "/projects/ach/ach-2.jpg",
          description: "Customer Database Management",
        },
        {
          id: 4,
          image: "/projects/ach/ach-3.jpg",
          description: "Data Visualization Dashboard",
        },
        {
          id: 5,
          image: "/projects/ach/ach-4.jpg",
          description: "Advanced Search & Filtering",
        },
        {
          id: 6,
          image: "/projects/ach/ach-5.jpg",
          description: "Customer Profile View",
        },
        {
          id: 7,
          image: "/projects/ach/ach-6.jpg",
          description: "Custom Invoice Generation",
        },
        {
          id: 8,
          image: "/projects/ach/ach-7.jpg",
          description: "Automated Expiration Alerts",
        },
        {
          id: 9,
          image: "/projects/ach/ach-8.jpg",
          description: "Analytics & Insights",
        },
        {
          id: 10,
          image: "/projects/ach/ach-9.jpg",
          description: "Export & Reporting Tools",
        },
        {
          id: 11,
          image: "/projects/ach/ach-10.jpg",
          description: "Settings & Configuration",
        },
      ],
      backgroundGradient: "from-blue-500 to-white",
      deviceType: "mobile",
      osTypes: ["android"],
      functionality:
        "A full-featured insurance contract management solution that supports Excel file import and processing, maintains a structured customer database, offers powerful search and filtering, provides insightful data visualizations, generates custom invoices, and delivers automated contract expiration reminders. " +
        "The application is built natively for Android using **Kotlin** for modern, concise, and maintainable code, with **Java** supporting compatibility and integration with legacy libraries. **SQLite** serves as the local database engine for secure offline data storage, while **Room Database** provides an abstraction layer for easier data management and efficient queries. This technology stack ensures robust performance, offline capability, and smooth user experience across devices.",
      repoLink: "https://github.com/kodage111/assurance-contract-handler",
      techStack: ["Kotlin", "Java", "SQLite", "Room Database"],
    },
  ];

  static readonly devIcons = this.stacks.map((stack) => ({
    name: stack.name,
    icon: stack.icon,
  }));
  static readonly topProjects: Project[] = this.featuredProjects.slice(0, 3);
  static readonly numberOfProjects = this.featuredProjects.length;
}
